project:
  type: website
  output-dir: docs
  render:
    - "!temp/"
    - "*.qmd"
    - "tech_blogs/"
    - "non_tech_blogs/"
  

website:
  site-url: https://aman5319.github.io/portfolio/
  title: "Aman Pandey"
  description: 'Sharing My Journey and Learning'

  repo-url: https://github.com/aman5319/portfolio
  repo-actions: [edit, issue]

  back-to-top-navigation: true
  reader-mode: true
  page-navigation: true
  open-graph: true
  page-footer:
    left: "Blog made with 💜 and [Quarto](https://quarto.org/), by Aman Pandey. License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
    right:
      - icon: envelope
        href: mailto:amanpandey@mailfence.com
  navbar:
    left:
      - text: Tech Blogs
        href: tech_blogs
      - text: Non Tech Blogs
        href: non_tech_blogs
  comments: 
    giscus:
      repo: aman5319/portfolio
      category: Q&A
      repo-id: R_kgDOJ44pkw
      category-id: DIC_kwDOJ44pk84CXwVt
      mapping: title
      reactions-enabled: true
      loading: lazy
    
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    code-copy: true
    code-overflow: wrap
    smooth-scroll: true
    link-external-icon: false
    link-external-newwindow: true
    citations-hover: true
    footnotes-hover: true
    toc: true
    code-link: true

freeze: auto
toc: true

editor: visual