project:
  type: website
  output-dir: docs
  

website:
  back-to-top-navigation: true
  reader-mode: true
  page-navigation: true
  title: "Aman Pandey | Data Scientist"
  navbar:
    right:
      - about.qmd
      - non_job.qmd
      - job.qmd
      - icon: github
        href: https://github.com/aman5319
      - icon: linkedin
        href: https://www.linkedin.com/in/aman5319/
format:
  html:
    theme: cosmo
    css: styles.css

freeze: auto
toc: true

editor: visual

