project:
  type: website
  output-dir: docs
  

website:
  site-url: https://aman5319.github.io/portfolio/
  description: 'Sharing My Journey and Learning'

  repo-url: https://github.com/aman5319/portfolio
  repo-actions: [edit, issue]

  back-to-top-navigation: true
  reader-mode: true
  page-navigation: true
  open-graph: true
  page-footer:
    left: "Blog made with 💜 and [Quarto](https://quarto.org/), by Aman Pandey. License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
    right:
      - icon: envelope
        href: mailto:amanpandey@mailfence.com
  sidebar: 
    contents: posts
    style: "docked"
  title: "Aman Pandey | Data Scientist"
  navbar:

    left:
      - icon: file-person
        text: About
        href: about.qmd
      - icon: file-pdf
        text: Resume
        href: https://drive.google.com/drive/folders/1pTPR0vPX1UoQYfyvQLu8Pn-Wc6hqrjGf?usp=sharing        
        target: _blank
    right:
      - icon: github
        href: https://github.com/aman5319
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/aman5319/
        target: _blank
  comments: 
    giscus:
      repo: aman5319/portfolio
      category: Q&A
      repo-id: R_kgDOJ44pkw
      category-id: DIC_kwDOJ44pk84CXwVt
      mapping: title
      reactions-enabled: true
      loading: lazy
    
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    code-copy: true
    code-overflow: wrap
    smooth-scroll: true
    link-external-icon: false
    link-external-newwindow: true
    citations-hover: true
    footnotes-hover: true
    toc: true
    code-link: true

freeze: auto
toc: true

editor: visual
